### ISSUE TITLE
Letter spacing and Line height

### ISSUE THREAD

**Issue by ldemyanenko** [roberto198907/zeplin-flutter-extended#3]
Please add Letter spacing and Line height params to the plugin output in case of TextStyles.

Currently flutter code looks this way
1)
From Zeplin - 
SFUIDisplay, Black
, 32pt
#white
Center, Letter spacing: 5pt

Flutter code - 
static const vS/64ScoreBlackWhite = const TextStyle(
    color:  Colors.white,
    fontWeight: FontWeight.w900,
    fontFamily: "SFUIDisplay",
    fontStyle:  FontStyle.normal,
    fontSize: 32.0
  );
2)
From Zeplin - 
SFUIDisplay, Heavy
, 20pt
#white
Line height: 24pt, Letter spacing: -0.1pt

Flutter code - 
  static const cards/Question/Title40HeavyLight = const TextStyle(
    color:  Colors.white,
    fontWeight: FontWeight.w900,
    fontFamily: "SFUIDisplay",
    fontStyle:  FontStyle.normal,
    fontSize: 20.0
  );

**Comment by roberto198907** [comment]
Hi @ldemyanenko 

Letter Spacing is implemented in this version, however, there is a fix with this, because you will find a colon two times (see attachment). I will be working on Line Height for the next version that would be updated in the next days. 
<img width="248" alt="Captura de Pantalla 2019-07-16 a la(s) 18 31 07" src="https://user-images.githubusercontent.com/48741699/61338712-fcb51f80-a7f7-11e9-995a-9c75a37150f4.png">

**Comment by roberto198907** [comment]
The version is now updated, this and other bugs have been solved.
